# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/image.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/image.proto\x12\x05image\"6\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\nimage_name\x18\x02 \x01(\t\"\x1c\n\nImageReply\x12\x0e\n\x06status\x18\x01 \x01(\t2C\n\x0cImageService\x12\x33\n\tSendImage\x12\x13.image.ImageRequest\x1a\x11.image.ImageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=29
  _globals['_IMAGEREQUEST']._serialized_end=83
  _globals['_IMAGEREPLY']._serialized_start=85
  _globals['_IMAGEREPLY']._serialized_end=113
  _globals['_IMAGESERVICE']._serialized_start=115
  _globals['_IMAGESERVICE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
